spring.application.name=Automated Monitoring & Analytics System

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL)
# ==========================================
# Cambia 'monitoreo_db' por el nombre de la base de datos que creaste en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoreo_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# EL TRUCO ESTÁ AQUÍ: 'update' crea las tablas si no existen y las actualiza si hay cambios en los Entities
spring.jpa.hibernate.ddl-auto=update

# El dialecto asegura que Hibernate hable el "PostgreSQL" correcto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONSOLA Y DEPURACIÓN (Opcional pero recomendado)
# ==========================================
# Muestra en la consola de IntelliJ el SQL que Spring genera por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DEL ORQUESTADOR (Tu servicio personalizado)
# ==========================================
# Ruta donde el backend generará el archivo para Prometheus
prometheus.config.path=./prometheus.yml
prometheus.api.url=http://localhost:9090
jwt.secret.key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970